---
include:
- "**/*.rb"
exclude:
- spec/**/*
- test/**/*
- vendor/**/*
- ".bundle/**/*"
require:
  - sinatra/base
domains:
  - Class<Sinatra::Base>
  - Class<Sinatra::Application>
reporters:
- rubocop
- require_not_found
plugins:
- runtime
require_paths: []
max_files: 5000
